enableGlobalCache: false

enableNetwork: true
enableImmutableInstalls: false

enableTelemetry: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@algolia/autocomplete-core@*":
    peerDependencies:
      "@algolia/client-search": "*"
      algoliasearch: "*"
      search-insights: "*"
  "@algolia/autocomplete-plugin-algolia-insights@*":
    peerDependencies:
      "@algolia/client-search": "*"
      algoliasearch: "*"
  "@docsearch/react@*":
    peerDependencies:
      "@algolia/client-search": "*"
  "@docusaurus/bundler@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/plugin-content-blog@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-content-docs@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-content-pages@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/preset-classic@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/theme-live-codeblock@*":
    peerDependencies:
      "@mdx-js/react": "*"
      "@docusaurus/plugin-content-docs": "*"
  "@docusaurus/plugin-css-cascade-layers@*":
    peerDependencies:
      "@mdx-js/react": "*"
      react: "*"
      react-dom: "*"
  "@docusaurus/plugin-debug@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-google-analytics@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-google-gtag@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-google-tag-manager@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-sitemap@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-svgr@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/theme-search-algolia@*":
    peerDependencies:
      "@mdx-js/react": "*"
      "@algolia/client-search": "*"
      search-insights: "*"
  "@docusaurus/utils-common@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/utils@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@mdx-js/mdx@*":
    peerDependencies:
      acorn: "*"
  "@docusaurus/babel@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/mdx-loader@*":
    peerDependencies:
      acorn: "*"
  "@docusaurus/preset-classic@*":
    peerDependencies:
      "@algolia/client-search": "*"
      search-insights: "*"
  "@docusaurus/types@*":
    peerDependencies:
      acorn: "*"
  "@docusaurus/utils-validation@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
