# Yarn 4 Configuration - Optimized for Monorepo Workspaces
# Last Updated: 2025-01-16

# Cache Configuration
enableGlobalCache: true         # Share cache across projects for better performance
compressionLevel: mixed          # Use mixed compression for balance of speed and size
cacheFolder: "./.yarn/cache"    # Keep cache in project for zero-installs capability

# Network Configuration
enableNetwork: true
enableHardenedMode: false  # Set to true in CI for security
npmRegistryServer: "https://registry.npmjs.org"

# Installation Configuration
enableImmutableInstalls: false    # Set to true in CI for reproducible installs
enableTelemetry: false

# Linker Configuration
# Using node-modules for Railway compatibility
# Consider PnP for better performance once deployment is stable
nodeLinker: node-modules

# Workspace Configuration
nmMode: hardlinks-local         # Use hardlinks for better performance

# Security & Performance
enableStrictSsl: true
httpTimeout: 60000
httpRetry: 3

# Progress bars (disable in CI)
enableProgressBars: true
enableColors: true

# Install State
installStatePath: "./.yarn/install-state.gz"

packageExtensions:
  "@algolia/autocomplete-core@*":
    peerDependencies:
      "@algolia/client-search": "*"
      algoliasearch: "*"
      search-insights: "*"
  "@algolia/autocomplete-plugin-algolia-insights@*":
    peerDependencies:
      "@algolia/client-search": "*"
      algoliasearch: "*"
  "@docsearch/react@*":
    peerDependencies:
      "@algolia/client-search": "*"
  "@docusaurus/bundler@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/plugin-content-blog@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-content-docs@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-content-pages@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/preset-classic@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/theme-live-codeblock@*":
    peerDependencies:
      "@mdx-js/react": "*"
      "@docusaurus/plugin-content-docs": "*"
  "@docusaurus/plugin-css-cascade-layers@*":
    peerDependencies:
      "@mdx-js/react": "*"
      react: "*"
      react-dom: "*"
  "@docusaurus/plugin-debug@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-google-analytics@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-google-gtag@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-google-tag-manager@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-sitemap@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/plugin-svgr@*":
    peerDependencies:
      "@mdx-js/react": "*"
  "@docusaurus/theme-search-algolia@*":
    peerDependencies:
      "@mdx-js/react": "*"
      "@algolia/client-search": "*"
      search-insights: "*"
  "@docusaurus/utils-common@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/utils@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@mdx-js/mdx@*":
    peerDependencies:
      acorn: "*"
  "@docusaurus/babel@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/mdx-loader@*":
    peerDependencies:
      acorn: "*"
  "@docusaurus/preset-classic@*":
    peerDependencies:
      "@algolia/client-search": "*"
      search-insights: "*"
  "@docusaurus/types@*":
    peerDependencies:
      acorn: "*"
  "@docusaurus/utils-validation@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
