[phases.setup]
nixPkgs = ["nodejs", "yarn", "python311"]

[phases.install]
cmds = [
    "cd packages/web && yarn install",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd packages/web && yarn build"
]

[start]
cmd = "python run_server.py"