[phases.setup]
nixpkgs = ["nodejs_20", "python312", "yarn"]
aptPkgs = ["build-essential", "git"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "corepack enable",
  "corepack prepare yarn@4.9.2 --activate",
  "python -m venv /app/.venv",
  "/app/.venv/bin/pip install --upgrade pip setuptools wheel",
  "/app/.venv/bin/pip install -r requirements.txt"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "yarn install --frozen-lockfile",
  "cd packages/web && yarn install --frozen-lockfile && yarn build && NEXT_OUTPUT_EXPORT=true yarn export"
]

[start]
cmd = "/app/.venv/bin/python /app/run_server.py"
