[phases.setup]
nixPkgs = ["python313", "nodejs_20", "yarn"]

[phases.install]
cmds = [
    "yarn install",
    "yarn workspace @monkey-coder/web export",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "python run_server.py"