[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
providers = ["node"]

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs-20_x"]

[build.nixpacksPlan.phases.install]
cmds = [
    "corepack enable",
    "corepack prepare yarn@4.9.2 --activate",
    "yarn install --immutable"
]

[build.nixpacksPlan.phases.build]
cmds = [
    "yarn workspace @monkey-coder/web build",
    "npm install -g serve@14.2.4"
]

[build.nixpacksPlan.start]
cmd = "serve -s packages/web/out -l $PORT -c serve.json"

[[build.env]]
name = "NODE_ENV"
value = "production"

[[build.env]]
name = "NEXT_TELEMETRY_DISABLED"
value = "1"

[[build.env]]
name = "NEXT_OUTPUT_EXPORT"
value = "true"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
