[build]
# Use Dockerfile for deployment
builder = "dockerfile"
# Use the optimized Dockerfile we've created
dockerfilePath = "Dockerfile"

[deploy]
# Health check configuration following Railway best practices
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"
restartPolicyMaxRetries = 3

# Resource configuration optimized for AI workloads
# Adjust based on usage patterns
[deploy.resources]
# Railway default resources are sufficient for initial deployment
# Can be scaled up based on usage metrics

[deploy.environment]
# Production environment settings
NODE_ENV = "production"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"

# Railway automatically provides PORT environment variable
# Our Dockerfile uses ARG PORT with fallback to 8000

[build.environment]
# Environment variables available during build
# Secrets should be set in Railway dashboard, not here
NODE_ENV = "production"

# Railway build optimizations
[build.watchIgnore]
# Ignore files that don't affect the build
ignorePatterns = [
    "*.md",
    "docs/**",
    ".git/**",
    ".vscode/**",
    "*.log",
    "node_modules/**",
    "__pycache__/**",
    "*.pyc",
    ".pytest_cache/**",
    "coverage/**",
    ".coverage",
    "*.test.*",
    "test/**"
]