[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd packages/core && python -m uvicorn monkey_coder.app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
variables = { }

[environments.staging] 
variables = { }
