"""
Context management system for multi-turn conversations.
Generated by Monkey Coder using GPT-4.1.
"""

from .manager import (
    ContextManager,
    Session,
    Message,
)

from .simple_manager import (
    SimpleContextManager,
    SimpleMessage,
    SimpleConversation,
    get_simple_context_manager,
)

__all__ = [
    "ContextManager",
    "Session", 
    "Message",
    "SimpleContextManager",
    "SimpleMessage",
    "SimpleConversation",
    "get_simple_context_manager",
]
