groups:
  - name: monkey_coder_alerts
    rules:
      # High error rate alert
      - alert: HighErrorRate
        expr: rate(monkey_coder_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
          service: monkey-coder
        annotations:
          summary: "High error rate detected in Monkey Coder"
          description: "Error rate is {{ $value }} errors per second for task type {{ $labels.task_type }}"

      # High latency alert
      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(monkey_coder_execution_duration_seconds_bucket[5m])) > 30
        for: 5m
        labels:
          severity: warning
          service: monkey-coder
        annotations:
          summary: "High execution latency detected"
          description: "95th percentile latency is {{ $value }} seconds for {{ $labels.task_type }}"

      # Service down alert
      - alert: ServiceDown
        expr: up{job="monkey-coder-core"} == 0
        for: 1m
        labels:
          severity: critical
          service: monkey-coder
        annotations:
          summary: "Monkey Coder Core service is down"
          description: "The Monkey Coder Core API is not responding"

      # Too many active executions
      - alert: TooManyActiveExecutions
        expr: monkey_coder_active_executions > 100
        for: 5m
        labels:
          severity: warning
          service: monkey-coder
        annotations:
          summary: "Too many active executions"
          description: "There are {{ $value }} active executions, which may indicate a bottleneck"

      # High token usage rate
      - alert: HighTokenUsage
        expr: rate(monkey_coder_tokens_total[5m]) > 1000
        for: 10m
        labels:
          severity: warning
          service: monkey-coder
        annotations:
          summary: "High token usage rate detected"
          description: "Token usage rate is {{ $value }} tokens per second for provider {{ $labels.provider }}"

      # Authentication errors
      - alert: AuthenticationErrors
        expr: rate(monkey_coder_errors_total{error_type="auth_error"}[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
          service: monkey-coder
        annotations:
          summary: "Authentication errors detected"
          description: "Authentication error rate is {{ $value }} per second"

      # Rate limit errors
      - alert: RateLimitErrors
        expr: rate(monkey_coder_errors_total{error_type="rate_limit_error"}[5m]) > 0.02
        for: 5m
        labels:
          severity: warning
          service: monkey-coder
        annotations:
          summary: "Rate limit errors detected"
          description: "Rate limit error rate is {{ $value }} per second for {{ $labels.task_type }}"
