global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "monkey_coder_alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Monkey Coder Core API
  - job_name: 'monkey-coder-core'
    static_configs:
      - targets: ['monkey-coder-core:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # Monkey Coder CLI metrics (if running as service)
  - job_name: 'monkey-coder-cli'
    static_configs:
      - targets: ['monkey-coder-cli:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s

  # Docker containers (if using cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
