site_name: Monkey Coder Documentation
site_description: AI-powered code generation and analysis platform based on Qwen3-Coder
site_author: GaryOcean428
site_url: https://garyocean428.github.io/monkey-coder

repo_name: GaryOcean428/monkey-coder
repo_url: https://github.com/GaryOcean428/monkey-coder

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - CLI Reference:
    - Commands: cli/commands.md
    - Examples: cli/examples.md
  - Core API:
    - Code Generation: api/generation.md
    - Code Analysis: api/analysis.md
  - SDK:
    - TypeScript: sdk/typescript.md
    - Python: sdk/python.md
  - Examples:
    - Basic Usage: examples/basic.md
    - Advanced Features: examples/advanced.md
  - Contributing: contributing.md
  - License: license.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
