name: Publish Packages

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Setup Yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Publish CLI to npm
        run: |
          cd packages/cli
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

  publish-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build and publish core package
        run: |
          cd packages/core
          python -m build
          python -m twine upload dist/* -u __token__ -p "${{ secrets.PYPI_TOKEN }}"

      - name: Build and publish SDK package
        run: |
          cd packages/sdk
          python -m build
          python -m twine upload dist/* -u __token__ -p "${{ secrets.PYPI_TOKEN }}"

  deploy-railway:
    runs-on: ubuntu-latest
    needs: [publish-npm, publish-pypi]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Railway
        uses: railwayapp/railway-deploy@v2
        with:
          railway-token: ${{ secrets.RAILWAY_TOKEN }}
          service: monkey-coder-api
